/* tslint:disable */
/* eslint-disable */
/**
 * toban API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * assignment of role
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * assignment id
     * @type {number}
     * @memberof Assignment
     */
    id: number;
    /**
     * role id
     * @type {number}
     * @memberof Assignment
     */
    roleId: number;
    /**
     * date when assignment start
     * @type {Date}
     * @memberof Assignment
     */
    startAt: Date;
    /**
     * date when assignment end (inclusive)
     * @type {Date}
     * @memberof Assignment
     */
    endAt: Date;
    /**
     * member id
     * @type {number}
     * @memberof Assignment
     */
    memberId: number;
}

export function AssignmentFromJSON(json: any): Assignment {
    return AssignmentFromJSONTyped(json, false);
}

export function AssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'roleId': json['role_id'],
        'startAt': (new Date(json['start_at'])),
        'endAt': (new Date(json['end_at'])),
        'memberId': json['member_id'],
    };
}

export function AssignmentToJSON(value?: Assignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'role_id': value.roleId,
        'start_at': (value.startAt.toISOString().substr(0,10)),
        'end_at': (value.endAt.toISOString().substr(0,10)),
        'member_id': value.memberId,
    };
}


