/* tslint:disable */
/* eslint-disable */
/**
 * toban API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * new member
 * @export
 * @interface NewMember
 */
export interface NewMember {
    /**
     * name of the member
     * @type {string}
     * @memberof NewMember
     */
    name: string;
}

export function NewMemberFromJSON(json: any): NewMember {
    return NewMemberFromJSONTyped(json, false);
}

export function NewMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NewMemberToJSON(value?: NewMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


