/* tslint:disable */
/* eslint-disable */
/**
 * toban API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * role
 * @export
 * @interface NewRole
 */
export interface NewRole {
    /**
     * name of the role
     * @type {string}
     * @memberof NewRole
     */
    name: string;
    /**
     * emoji icon key of the role (e.g. '+1', 'tada')
     * @type {string}
     * @memberof NewRole
     */
    emoji?: string;
}

export function NewRoleFromJSON(json: any): NewRole {
    return NewRoleFromJSONTyped(json, false);
}

export function NewRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'emoji': !exists(json, 'emoji') ? undefined : json['emoji'],
    };
}

export function NewRoleToJSON(value?: NewRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'emoji': value.emoji,
    };
}


