openapi: "3.0.0"
info:
  title: toban API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: dev
paths:
  /members:
    get:
      operationId: get_members
      summary: get members
      responses:
        '200':
          description: |
            200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
    post:
      operationId: post_members
      summary: post a new member
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMember'
      responses:
        '201':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/New'

  /members/{member_id}:
    get:
      operationId: get_members_member_id
      summary: get a member
      parameters:
        - name: member_id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
  /roles:
    get:
      operationId: get_roles
      summary: get roles
      responses:
        '200':
          description:
            Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
  /roles/{role_id}:
    get:
      operationId: get_roles_role_id
      summary: get a role
      parameters:
        - name: role_id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      description: general error response
      type: object
      properties:
        code:
          description: application specific error code
          type: string
        message:
          description: human readable error message
          type: string
    New:
      description: general response for posting new resource
      type: object
      properties:
        id:
          type: integer
          format: int32
      required: [id]
    Member:
      description: member
      type: object
      properties:
        id:
          description: member id
          type: integer
          format: int32
        name:
          description: name of the member
          type: string
      required: [id, name]
    NewMember:
      description: new member
      type: object
      properties:
        name:
          description: name of the member
          type: string
      required: [name]
    Role:
      description: member
      type: object
      properties:
        id:
          description: role id
          type: integer
          format: int32
        name:
          description: name of the role
          type: string
        emoji:
          description: emoji icon key of the role (e.g. '+1', 'tada')
          type: string
      required: [id, name]
