openapi: "3.0.0"
info:
  title: toban API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: dev
paths:
  /members:
    $ref: './components/member.yaml#/components/pathItems/~1members'
  /members/{member_id}:
    $ref: './components/member.yaml#/components/pathItems/~1members~1{member_id}'
  /roles:
    $ref: './components/role.yaml#/components/pathItems/~1roles'
  /roles/{role_id}:
    $ref: './components/role.yaml#/components/pathItems/~1roles~1{role_id}'
  /assignments:
    $ref: './components/assignment.yaml#/components/pathItems/~1assignments'
components:
  schemas:
    Error:
      $ref: './components/general.yaml#/components/schemas/Error'
