openapi: "3.0.0"
info:
  title: toban API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: dev
paths:
  /members:
    get:
      operationId: get_members
      summary: get members
      responses:
        '200':
          description: |
            200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
  /members/{member_id}:
    get:
      operationId: get_members_member_id
      summary: get a member
      parameters:
        - name: member_id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: |
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '404':
          description: |
            404 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      description: general error response
      type: object
      properties:
        code:
          description: application specific error code
          type: string
        message:
          description: human readable error message
          type: string
    Member:
      description: member
      type: object
      properties:
        id:
          description: member id
          type: integer
          format: int32
        name:
          description: name of the member
          type: string
      required: [id, name]
